### ISSUE TITLE
library not found for -ljschelpers

### ISSUE THREAD

**Issue by 452MJ** [SurpassRabbit/ShiTu#13]
我按照相关教程跟你的工程，升级自己的APP，编译ios 的时候遇到`library not found for -ljschelpers`
![image](https://user-images.githubusercontent.com/13673008/54805381-c0423e80-4cb1-11e9-9988-2d8b711a72ee.png)

请问你有遇到过吗？

**Comment by 452MJ** [comment]
升级到0.57.5还是OK的，升级到0.58.4的时候提示这个错误，然后我尝试继续升级到0.59.0，依然报找不到这个库，浏览了下library，没看到有这个名字的痕迹

**Comment by SurpassRabbit** [comment]
你咋升级的?

**Comment by 452MJ** [comment]
[rn-diff-purge](https://github.com/react-native-community/rn-diff-purge/compare/version/0.57.5...version/0.59.0)

手动升级的

**Comment by SurpassRabbit** [comment]
我是迁移的。

**Comment by 452MJ** [comment]
初步判断是因为0.59使用了JSFrameCore的原因。底层代码改动比较大，引入库失败的问题

**Comment by CodeRabbitYu** [comment]
0.59的更新很大
