### ISSUE TITLE
react-native run-ios报错

### ISSUE THREAD

**Issue by weiyang123** [SurpassRabbit/ShiTu#4]
Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ShiTu.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by csdwd** [comment]
我的也是,    这个该怎么解决呢

**Comment by XHTeng** [comment]
用 yarn 命令安装， 直接yarn 就可以
