### ISSUE TITLE
android

### ISSUE THREAD

**Issue by duanzjun** [SurpassRabbit/ShiTu#5]
android版在瀑布流里面，很多图片一直转圈无法加载出来。我使用FlatList插件加载图片也有这个问题 
![wechatimg4](https://user-images.githubusercontent.com/2028243/33756207-5cd84040-dc2f-11e7-932a-072736c9f679.jpeg)

**Comment by SurpassRabbit** [comment]
是的。这个如果去掉加载的菊花，应该是可以正确展示的。就是不太美观，我也就没有处理。
